name: BanDiscordLogger
version: '1.2-SNAPSHOT'
main: dev.omochi.bandiscordlogger.BanDiscordLogger
api-version: 1.18
commands:
  autoban:
    aliases: [ aban ]
    description: ipban及びbanを自動的に実行し、discordにログを残します
    permission: bandiscordlogger.commands.autoban
    usage: /aban [player名] [reason（理由）]
permissions:
  bandiscordlogger.*:
    children:
      bandiscordlogger.commands: true
    description: bandiscordloggerを全部使える。
    default: op